// Code generated by protoc-gen-go. DO NOT EDIT.
// source: streaming.proto

/*
Package streaming is a generated protocol buffer package.

It is generated from these files:
	streaming.proto

It has these top-level messages:
	FileUAST
	Empty
*/
package streaming

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileUAST struct {
	File string `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Uast string `protobuf:"bytes,2,opt,name=uast" json:"uast,omitempty"`
}

func (m *FileUAST) Reset()                    { *m = FileUAST{} }
func (m *FileUAST) String() string            { return proto.CompactTextString(m) }
func (*FileUAST) ProtoMessage()               {}
func (*FileUAST) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FileUAST) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *FileUAST) GetUast() string {
	if m != nil {
		return m.Uast
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*FileUAST)(nil), "streaming.FileUAST")
	proto.RegisterType((*Empty)(nil), "streaming.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for StreamingService service

type StreamingServiceClient interface {
	ParseUAST(ctx context.Context, in *Empty, opts ...grpc.CallOption) (StreamingService_ParseUASTClient, error)
}

type streamingServiceClient struct {
	cc *grpc.ClientConn
}

func NewStreamingServiceClient(cc *grpc.ClientConn) StreamingServiceClient {
	return &streamingServiceClient{cc}
}

func (c *streamingServiceClient) ParseUAST(ctx context.Context, in *Empty, opts ...grpc.CallOption) (StreamingService_ParseUASTClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_StreamingService_serviceDesc.Streams[0], c.cc, "/streaming.StreamingService/ParseUAST", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamingServiceParseUASTClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamingService_ParseUASTClient interface {
	Recv() (*FileUAST, error)
	grpc.ClientStream
}

type streamingServiceParseUASTClient struct {
	grpc.ClientStream
}

func (x *streamingServiceParseUASTClient) Recv() (*FileUAST, error) {
	m := new(FileUAST)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for StreamingService service

type StreamingServiceServer interface {
	ParseUAST(*Empty, StreamingService_ParseUASTServer) error
}

func RegisterStreamingServiceServer(s *grpc.Server, srv StreamingServiceServer) {
	s.RegisterService(&_StreamingService_serviceDesc, srv)
}

func _StreamingService_ParseUAST_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamingServiceServer).ParseUAST(m, &streamingServiceParseUASTServer{stream})
}

type StreamingService_ParseUASTServer interface {
	Send(*FileUAST) error
	grpc.ServerStream
}

type streamingServiceParseUASTServer struct {
	grpc.ServerStream
}

func (x *streamingServiceParseUASTServer) Send(m *FileUAST) error {
	return x.ServerStream.SendMsg(m)
}

var _StreamingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.StreamingService",
	HandlerType: (*StreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ParseUAST",
			Handler:       _StreamingService_ParseUAST_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "streaming.proto",
}

func init() { proto.RegisterFile("streaming.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2e, 0x29, 0x4a,
	0x4d, 0xcc, 0xcd, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x19, 0x71, 0x71, 0xb8, 0x65, 0xe6, 0xa4, 0x86, 0x3a, 0x06, 0x87, 0x08, 0x09, 0x71, 0xb1, 0xa4,
	0x65, 0xe6, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x20, 0xb1, 0xd2, 0xc4,
	0xe2, 0x12, 0x09, 0x26, 0x88, 0x18, 0x88, 0xad, 0xc4, 0xce, 0xc5, 0xea, 0x9a, 0x5b, 0x50, 0x52,
	0x69, 0xe4, 0xc5, 0x25, 0x10, 0x0c, 0x33, 0x29, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8,
	0x8c, 0x8b, 0x33, 0x20, 0xb1, 0xa8, 0x18, 0x62, 0xa2, 0x80, 0x1e, 0xc2, 0x6a, 0xb0, 0x16, 0x29,
	0x61, 0x24, 0x11, 0x98, 0xc5, 0x4a, 0x0c, 0x06, 0x8c, 0x49, 0x6c, 0x60, 0xa7, 0x19, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x86, 0x57, 0x9e, 0x83, 0xad, 0x00, 0x00, 0x00,
}
